---
title: "Shopify DS"
author: "Victoria Okoro"
date: "1/17/2022"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(plotly)
library(cowplot)

```

```{r}
df <- read.csv("~/Documents/Shopify/Copy of 2019 Winter Data Science Intern Challenge Data Set - Sheet1.csv")

```


```{r}
summary(df$order_amount)

median(df$order_amount)

```


```{r} 
df$total_items <- sort(df$total_items)

bp <- ggplot(data = df, aes(x = total_items)) + 
  geom_bar(fill = "purple") +  ggtitle("Distribution of Items Bought.") + xlim(0,8) +
  xlab("Total Items") 

ggplotly(bp)

df2 <- df[4984:5000, ] 
df2$total_items <- sort(df2$total_items)

bp2 <- ggplot(data = df2, aes(x = total_items)) + 
  geom_bar(fill = "purple", width = 140) + 
  ggtitle("Distribution of Items Bought.") + xlim(1000,2500) +
  xlab("Total Items") 

ggplotly(bp2)

bp_grid <- plot_grid(bp, bp2, labels = "AUTO") 

bp_grid


```

Summary:

The median is the best indicator for how much a customer usually spends on sneakers given they are a relatively affordable, rather than using the mean. For my visualization I illustrated the frequency of the amount of items customers bought. Majority of customers bought between 1 to 3 items. Only a small amount of customers bought 2000 items. The count is:

1 -> 1830
2 -> 1832
3 -> 941
4 -> 293
5 -> 77
6 -> 9
2000 -> 17







